@startuml
title Emacs Preview

actor me

node Emacs {
    usecase "Modify PlantUML code" as modify
    usecase "Set image url to vue file" as vue
}

node Vite <<server>> {
    usecase "Do HMR stuff" as hmr
}


node Browser {
    usecase "Preview diagram" as preview
    usecase "Display updated diagram" as display
}


node PlantUML <<server>> {
    usecase "Generate PlantUML diagram\nimage url" as generate
}

me --> modify
me --> preview
modify --> generate
generate -up-> vue
vue --> hmr
hmr -up-> display

' Stuff for display
preview -[hidden]-> display

@enduml
